version: '3'

services:
  senders:
    build: ./senders-service
    container_name: senders_service
    environment:
      - APP_API_PORT=3330
      - DB_NAME=senders
      - DB_USERNAME=senders
      - DB_PASSWORD=adB0OebSab1oj5Kv
      - DB_HOST=cluster0.llwh0.mongodb.net
    networks:
      - logistics-management-network
    ports:
      - '3330:3330'

  suppliers:
    build: ./suppliers-service
    container_name: suppliers_service
    environment:
      - APP_API_PORT=3331
      - DB_NAME=suppliers
      - DB_USERNAME=suppliers
      - DB_PASSWORD=uwmMpX9J8WtLIH2H
      - DB_HOST=cluster0.prysc.mongodb.net
    networks:
      - logistics-management-network
    ports:
      - '3331:3331'

  storages:
    build: ./storages-service
    container_name: storages_service
    environment:
      - APP_API_PORT=3332
      - DB_NAME=storages
      - DB_USERNAME=storages
      - DB_PASSWORD=8p0cYL2ODepNmt4K
      - DB_HOST=cluster0.ymx1e.mongodb.net
    networks:
      - logistics-management-network
    ports:
      - '3332:3332'

  products:
    build: ./products-service
    container_name: products_service
    environment:
      - APP_API_PORT=3333
      - DB_NAME=products
      - DB_USERNAME=products
      - DB_PASSWORD=kAdbZwJFU1u769pi
      - DB_HOST=cluster0.bw7lb.mongodb.net
      - KAFKA_HOST=kafka:29092
      - KAFKA_CLIENT_ID=logistics-services-management
      - STORAGE_CONTROL_TOPIC=storage-control
    networks:
      - logistics-management-network
    ports:
      - '3333:3333'

  reports:
    build: ./reports-service
    container_name: reports_service
    environment:
      - APP_API_PORT=3336
      - DB_NAME=reports
      - DB_USERNAME=reports
      - DB_PASSWORD=lmRX0EHEKaf4Xuu2
      - DB_HOST=cluster0.j2lwq.mongodb.net
    networks:
      - logistics-management-network
    ports:
      - '3336:3336'

  receivers:
    build: ./receivers-service
    container_name: receivers_service
    environment:
      - APP_API_PORT=3334
      - DB_NAME=receivers
      - DB_USERNAME=receivers
      - DB_PASSWORD=ATDJx5cjxVx7qvrM
      - DB_HOST=cluster0.gxar7.mongodb.net
    networks:
      - logistics-management-network
    ports:
      - '3334:3334'

  web-bff:
    build: ./web-bff-service
    container_name: web-bff-service
    environment:
      - APP_API_PORT=3000
      - API_REPORTS_ADDRESS=http://reports:3336
      - API_RECEIVERS_ADDRESS=http://receivers:3334
      - API_PRODUCTS_ADDRESS=http://products:3333
      - API_SENDERS_ADDRESS=http://senders:3330
      - API_STORAGES_ADDRESS=http://storages:3332
      - API_SUPPLIERS_ADDRESS=http://suppliers:3331
    networks:
      - logistics-management-network
    ports:
      - '3000:3000'

  orchestrator:
    build: ./orchestrator-service
    container_name: orchestrator-service
    environment:
      - APP_API_PORT=3335
      - API_REPORTS_ADDRESS=http://reports:3336
      - API_RECEIVERS_ADDRESS=http://receivers:3334
      - API_PRODUCTS_ADDRESS=http://products:3333
      - API_SENDERS_ADDRESS=http://senders:3330
      - API_STORAGES_ADDRESS=http://storages:3332
      - API_SUPPLIERS_ADDRESS=http://suppliers:3331
      - KAFKA_HOST=kafka:29092
      - KAFKA_CLIENT_ID=logistics-services-management
      - STORAGE_CONTROL_TOPIC=storage-control 
      - KAFKA_GROUP_ID=logistics-services     
    networks:
      - logistics-management-network
    ports:
      - '3335:3335'

  zookeeper:
    image: 'confluentinc/cp-zookeeper:5.2.1'
    container_name: 'zookeeper'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - logistics-management-network

  kafka:
    image: 'confluentinc/cp-enterprise-kafka:5.2.1'
    container_name: 'kafka'
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=0
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=INSIDE://kafka:29092,OUTSIDE://kafka:9092
      - KAFKA_ADVERTISED_LISTENERS=INSIDE://kafka:29092,OUTSIDE://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=100
      - KAFKAJS_NO_PARTITIONER_WARNING=1
    networks:
      - logistics-management-network

networks:
  logistics-management-network:
    driver: bridge
