version: '3'

services:
  senders:
    build: ./senders-service
    container_name: senders_service
    environment:
      - APP_API_PORT=3330
      - DB_NAME=senders
      - DB_USERNAME=senders
      - DB_PASSWORD=adB0OebSab1oj5Kv
      - DB_HOST=cluster0.llwh0.mongodb.net
    networks:
      - logistics-management-network
    ports:
      - '3330:3330'

  suppliers:
    build: ./suppliers-service
    container_name: suppliers_service
    environment:
      - APP_API_PORT=3331
      - DB_NAME=suppliers
      - DB_USERNAME=suppliers
      - DB_PASSWORD=uwmMpX9J8WtLIH2H
      - DB_HOST=cluster0.prysc.mongodb.net
    networks:
      - logistics-management-network
    ports:
      - '3331:3331'

  storages:
    build: ./storages-service
    container_name: storages_service
    environment:
      - APP_API_PORT=3332
      - DB_NAME=storages
      - DB_USERNAME=storages
      - DB_PASSWORD=8p0cYL2ODepNmt4K
      - DB_HOST=cluster0.ymx1e.mongodb.net
    networks:
      - logistics-management-network
    ports:
      - '3332:3332'

  products:
    build: ./products-service
    container_name: products_service
    environment:
      - APP_API_PORT=3333
      - DB_NAME=products
      - DB_USERNAME=products
      - DB_PASSWORD=kAdbZwJFU1u769pi
      - DB_HOST=cluster0.bw7lb.mongodb.net
    networks:
      - logistics-management-network
    ports:
      - '3333:3333'

  receivers:
    build: ./receivers-service
    container_name: receivers_service
    environment:
      - APP_API_PORT=3334
      - DB_NAME=receivers
      - DB_USERNAME=receivers
      - DB_PASSWORD=ATDJx5cjxVx7qvrM
      - DB_HOST=cluster0.gxar7.mongodb.net
    networks:
      - logistics-management-network
    ports:
      - '3334:3334'

  web-bff:
    build: ./web-bff-service
    container_name: web-bff-service
    environment:
      - APP_API_PORT=3000
      - API_RECEIVERS_ADDRESS=http://receivers:3334
      - API_PRODUCTS_ADDRESS=http://products:3333
      - API_SENDERS_ADDRESS=http://senders:3330
      - API_STORAGES_ADDRESS=http://storages:3332
      - API_SUPPLIERS_ADDRESS=http://suppliers:3331
    networks:
      - logistics-management-network
    ports:
      - '3000:3000'

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - logistics-management-network

  kafka:
    image: 'bitnami/kafka:latest'
    container_name: 'kafka'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      - logistics-management-network
    depends_on:
      - zookeeper

networks:
  logistics-management-network:
    driver: bridge
