version: '3'

services:
  senders:
    build: ./senders-service
    container_name: senders_service
    networks:
      - logistics-management
    ports:
      - '3330:3330'

  suppliers:
    build: ./suppliers-service
    container_name: suppliers_service
    networks:
      - logistics-management
    ports:
      - '3331:3331'

  storages:
    build: ./storages-service
    container_name: storages_service
    networks:
      - logistics-management
    ports:
      - '3332:3332'

  products:
    build: ./products-service
    container_name: products_service
    networks:
      - logistics-management
    ports:
      - '3333:3333'

  receivers:
    build: ./receivers-service
    container_name: receivers_service
    networks:
      - logistics-management
    ports:
      - '3334:3334'

networks:
  logistics-management:
    driver: bridge
